// This file is automatically generated and enhanced for reliable auth verification.
import { createMiddleware } from '@tanstack/react-start';
import { getRequest } from '@tanstack/react-start/server';
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function parseJwtPayload(token: string): any {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) return null;
    const base64Url = parts[1];
    const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
    const jsonPayload = decodeURIComponent(
      atob(base64)
        .split('')
        .map((c) => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2))
        .join('')
    );
    return JSON.parse(jsonPayload);
  } catch (e) {
    return null;
  }
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const metaEnv = typeof import.meta !== 'undefined' && import.meta.env ? import.meta.env : ({} as Record<string, string>);
    const procEnv = typeof process !== 'undefined' && process.env ? process.env : ({} as Record<string, string>);

    let cfEnv: Record<string, string> = {};
    try {
      cfEnv = (globalThis as any).__rlsEnvCache || (globalThis as any).__cf_env || {};
    } catch (_) {}

    const gThis = typeof globalThis !== 'undefined' ? (globalThis as any) : {};

    const SUPABASE_URL =
      procEnv['SUPABASE_URL'] ||
      procEnv['VITE_SUPABASE_URL'] ||
      gThis['SUPABASE_URL'] ||
      cfEnv['SUPABASE_URL'] ||
      metaEnv['VITE_SUPABASE_URL'] ||
      metaEnv['SUPABASE_URL'] ||
      'https://mvbmkbkgjmvyvadhqbvu.supabase.co';

    const SUPABASE_PUBLISHABLE_KEY =
      procEnv['SUPABASE_PUBLISHABLE_KEY'] ||
      procEnv['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
      gThis['SUPABASE_PUBLISHABLE_KEY'] ||
      cfEnv['SUPABASE_PUBLISHABLE_KEY'] ||
      metaEnv['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
      metaEnv['SUPABASE_PUBLISHABLE_KEY'] ||
      'sb_publishable_ygKD2Pijsuxbh9K6kdmYjg_OC_3gykK';

    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    let userId: string | null = null;
    let claims: any = {};

    const payload = parseJwtPayload(token);
    if (payload && payload.sub) {
      userId = payload.sub;
      claims = payload;
    }

    if (!userId) {
      const { data: userData, error: userErr } = await supabase.auth.getUser(token);
      if (userErr || !userData?.user) {
        throw new Error('Unauthorized: Invalid token');
      }
      userId = userData.user.id;
      claims = { sub: userData.user.id, email: userData.user.email, ...userData.user.user_metadata };
    }

    return next({
      context: {
        supabase,
        userId,
        claims,
      },
    });
  },
);
