// This file is automatically generated and safely configured for client and SSR environments.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const metaEnv = typeof import.meta !== 'undefined' && import.meta.env ? import.meta.env : ({} as Record<string, string>);
  const procEnv = typeof process !== 'undefined' && process.env ? process.env : ({} as Record<string, string>);

  const SUPABASE_URL =
    metaEnv['VITE_SUPABASE_URL'] ||
    procEnv['VITE_SUPABASE_URL'] ||
    metaEnv['SUPABASE_URL'] ||
    procEnv['SUPABASE_URL'] ||
    'https://mvbmkbkgjmvyvadhqbvu.supabase.co';

  const SUPABASE_PUBLISHABLE_KEY =
    metaEnv['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
    procEnv['VITE_SUPABASE_PUBLISHABLE_KEY'] ||
    metaEnv['SUPABASE_PUBLISHABLE_KEY'] ||
    procEnv['SUPABASE_PUBLISHABLE_KEY'] ||
    'sb_publishable_Z1V67PzE6L34-N7L6J9X1Q';

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
